# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  # резолвер url'ов
  resolvers:
    default:
      web_path:
        web_root: '%kernel.root_dir%/../public'
        cache_prefix: 'media/cache'

  # конфигурируемые доступные DataLoader
  loaders:
    default:
      filesystem:
        data_root: '%kernel.root_dir%/../public'

  # настройки фильтров
  filter_sets:

    # CacheResolver по умолчанию
    cache: ~

    # конфигуриуем фильтры
    # название фильтра
    course_cover_in_list:
      quality: 95
      filters:
        thumbnail: { size: [890, 540], mode: outbound }

#  cache:        default
#  data_loader:  default

