vich_uploader:
  db_driver: orm

  mappings:
    course_covers:
      uri_prefix:         '%app.path.course_covers%'
      upload_destination: '%kernel.project_dir%/public%app.path.course_covers%'

    course_breadcrumbs:
      uri_prefix:         '%app.path.course_breadcrumbs%'
      upload_destination: '%kernel.project_dir%/public%app.path.course_breadcrumbs%'

    course_lesson_covers:
      uri_prefix:         '%app.path.course_lesson_cover%'
      upload_destination: '%kernel.project_dir%/public%app.path.course_lesson_cover%'