version: '2'

services:
    mysql:
        container_name: ${DOCKER_CONTAINERS_PREFIX}-db
        user: "${DOCKER_USER_ID}:${DOCKER_GROUP_ID}"
        build:
            context: mysql
            args:
                HOST_USER_ID: ${DOCKER_USER_ID}
                HOST_GROUP_ID: ${DOCKER_GROUP_ID}
        ports:
            - 33060:3306
        volumes:
            - ./mysql/config/conf.cnf:/etc/mysql/conf.d/conf.cnf
            - ./mysql/dump:/docker-entrypoint-initdb.d
            - ./mysql/data:/var/lib/mysql
            #- ./logs/mysql:/var/log
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DOCKER_DB_NAME}
            MYSQL_USER: ${DOCKER_DB_USER}
            MYSQL_PASSWORD: ${DOCKER_DB_PASSWORD}

    php:
        container_name: ${DOCKER_CONTAINERS_PREFIX}-php
        build:
            context: php
            args:
                HOST_USER_ID: ${DOCKER_USER_ID}
                HOST_GROUP_ID: ${DOCKER_GROUP_ID}
        volumes:
            - ${DOCKER_APP_PATH}:/var/www:cached

    nginx:
        container_name: ${DOCKER_CONTAINERS_PREFIX}-nginx
        build:
            context: nginx
            args:
                HOST_USER_ID: ${DOCKER_USER_ID}
                HOST_GROUP_ID: ${DOCKER_GROUP_ID}
        ports:
            - 8080:80
        volumes_from:
            - php